name: Publish Package to npmjs
on:
    pull_request:
        types:
            - closed
        branches:
            - "main"

jobs:
    build-and-publish:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            # Setup .npmrc file to publish to npm
            - uses: actions/setup-node@v3
              with:
                  node-version: "20.x"
                  registry-url: "https://registry.npmjs.org"
                  # Defaults to the user or organization that owns the workflow file
            - run: yarn

            - uses: JS-DevTools/npm-publish@v3.0.1
              with:
                  token: ${{ secrets.NPM_TOKEN }}
                  dry-run: false
